version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scoreplay_app
    environment:
      - POSTGRES_HOST=scoreplay_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=scoreplay
      - API_URL=http://localhost:8080
    ports:
      - "8080:8080"
    depends_on:
      - scoreplay_postgres

  scoreplay_postgres:
    image: postgres:14
    container_name: scoreplay_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=scoreplay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/tmp/data/postgres

volumes:
  postgres_data:
